=== dasch-swiss/dsp-tools/knora/dsplib/schemas/data.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="https://dasch.swiss/schema"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://dasch.swiss/schema"
           elementFormDefault="qualified">

    <!-- data type for resrefs "ID|ID|..." -->
    <xs:simpleType name="resrefs_type">
        <xs:restriction base="xs:token">
            <xs:pattern value="([^|]+)(\|[^|]+)*"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- group type for allow..." -->
    <xs:simpleType name="group_types">
        <xs:restriction base="xs:token">
            <xs:pattern
                value="(UnknownUser|KnownUser|ProjectMember|Creator|ProjectAdmin|SystemAdmin|([\w-]+):([\w ]+))"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- data type for knora date -->
    <xs:simpleType name="knoradate_type">
        <xs:restriction base="xs:token">
            <xs:pattern
                value="(GREGORIAN:|JULIAN:)?(CE:|BCE:)?(\d{4})?(-\d{1,2})?(-\d{1,2})?(:CE|:BCE)?(:\d{4})?(-\d{1,2})?(-\d{1,2})?"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- data type for knora color -->
    <xs:simpleType name="knoracolor_type">
        <xs:restriction base="xs:token">
            <xs:pattern value="#([0-9a-fA-F]{3}){1,2}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- data type for knora interval -->
    <xs:simpleType name="knorainterval_type">
        <xs:restriction base="xs:token">
            <xs:pattern value="([+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)):([+-]?([0-9]+([.][0-9]*)?|[.][0-9]+))"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- encoding types -->
    <xs:simpleType name="encoding_types">
        <xs:restriction base="xs:string">
            <xs:enumeration value="utf8"/>
            <xs:enumeration value="xml"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- text value type -->
    <xs:complexType name="text_type" mixed="true">
        <xs:sequence>
            <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="encoding" type="encoding_types" use="required"/>
        <xs:attribute name="resrefs" type="resrefs_type"/>
        <xs:attribute name="comment" type="xs:string"/>
        <xs:attribute name="permissions" type="xs:NCName" use="required"/>
    </xs:complexType>

    <!-- color value type -->
    <xs:complexType name="color_type">
        <xs:simpleContent>
            <xs:extension base="knoracolor_type">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- date value type -->
    <xs:complexType name="date_type">
        <xs:simpleContent>
            <xs:extension base="knoradate_type">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- float value type -->
    <xs:complexType name="float_type">
        <xs:simpleContent>
            <xs:extension base="xs:float">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- geometry value type -->
    <xs:complexType name="geometry_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- geoname value type -->
    <xs:complexType name="geoname_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- list value type -->
    <xs:complexType name="list_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- iconclass value type -->
    <xs:complexType name="iconclass_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- integer value type -->
    <xs:complexType name="integer_type">
        <xs:simpleContent>
            <xs:extension base="xs:integer">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- interval value type -->
    <xs:complexType name="interval_type">
        <xs:simpleContent>
            <xs:extension base="knorainterval_type">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- period value type -->
    <xs:complexType name="period_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="resptr_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- time value type -->
    <xs:complexType name="time_type">
        <xs:simpleContent>
            <xs:extension base="xs:dateTime">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- decimal value type -->
    <xs:complexType name="decimal_type">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- uri value type -->
    <xs:complexType name="uri_type">
        <xs:simpleContent>
            <xs:extension base="xs:anyURI">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- boolean value type -->
    <xs:complexType name="boolean_type">
        <xs:simpleContent>
            <xs:extension base="xs:boolean">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- textprop_type -->
    <xs:complexType name="textprop_type">
        <xs:sequence>
            <xs:element name="text" type="text_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- colorprop_type -->
    <xs:complexType name="colorprop_type">
        <xs:sequence>
            <xs:element name="color" type="color_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- dateprop_type -->
    <xs:complexType name="dateprop_type">
        <xs:sequence>
            <xs:element name="date" type="date_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- floatprop_type -->
    <xs:complexType name="floatprop_type">
        <xs:sequence>
            <xs:element name="float" type="float_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- geometryprop_type -->
    <xs:complexType name="geometryprop_type">
        <xs:sequence>
            <xs:element name="geometry" type="geometry_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- geonameprop_type -->
    <xs:complexType name="geonameprop_type">
        <xs:sequence>
            <xs:element name="geoname" type="geoname_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- listprop_type -->
    <xs:complexType name="listprop_type">
        <xs:sequence>
            <xs:element name="list" type="list_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="list" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- iconclassprop_type -->
    <xs:complexType name="iconclassprop_type">
        <xs:sequence>
            <xs:element name="iconclass" type="iconclass_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- integerprop_type -->
    <xs:complexType name="integerprop_type">
        <xs:sequence>
            <xs:element name="integer" type="integer_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- intervalprop_type -->
    <xs:complexType name="intervalprop_type">
        <xs:sequence>
            <xs:element name="interval" type="interval_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- periodprop_type -->
    <xs:complexType name="periodprop_type">
        <xs:sequence>
            <xs:element name="period" type="period_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- resptrprop_type -->
    <xs:complexType name="resptrprop_type">
        <xs:sequence>
            <xs:element name="resptr" type="resptr_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- timeprop_type -->
    <xs:complexType name="timeprop_type">
        <xs:sequence>
            <xs:element name="time" type="time_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- decimalprop_type -->
    <xs:complexType name="decimalprop_type">
        <xs:sequence>
            <xs:element name="decimal" type="decimal_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- uriprop_type -->
    <xs:complexType name="uriprop_type">
        <xs:sequence>
            <xs:element name="uri" type="uri_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- booleanprop_type -->
    <xs:complexType name="booleanprop_type">
        <xs:sequence>
            <xs:element name="boolean" type="boolean_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- bitsteeam tag -->
    <xs:complexType name="bitstream_type">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
    </xs:complexType>

    <!-- image tag -->
    <xs:complexType name="image_type">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
    </xs:complexType>

    <!-- sound tag -->
    <xs:complexType name="sound_type">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
    </xs:complexType>

    <!-- movie tag -->
    <xs:complexType name="movie_type">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
    </xs:complexType>

    <!-- movie tag -->
    <xs:complexType name="document_type">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
    </xs:complexType>

    <!-- resource tag -->
    <xs:complexType name="resource_type">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="1">
                <!--
                <xs:element name="image" type="image_type" />
                <xs:element name="sound" type="sound_type" />
                <xs:element name="movie" type="sound_type" />
                <xs:element name="document" type="sound_type" />
                -->
                <xs:element name="bitstream" type="sound_type"/>
            </xs:choice>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="text-prop" type="textprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="color-prop" type="colorprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="date-prop" type="dateprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="geometry-prop" type="geometryprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="geoname-prop" type="geonameprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="list-prop" type="listprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="iconclass-prop" type="iconclassprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="integer-prop" type="integerprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="interval-prop" type="intervalprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="period-prop" type="periodprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="resptr-prop" type="resptrprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="time-prop" type="timeprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="decimal-prop" type="decimalprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="uri-prop" type="uriprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="boolean-prop" type="booleanprop_type" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>

        </xs:sequence>
        <xs:attribute name="label" type="xs:string" use="required"/>
        <xs:attribute name="restype" type="xs:string" use="required"/>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="permissions" type="xs:NCName" use="required"/>
    </xs:complexType>

    <!-- data type for knora shortcode -->
    <xs:simpleType name="knorashortcode_type">
        <xs:restriction base="xs:token">
            <xs:pattern value="[0-9a-fA-F]{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- data type for valid permissions_type" -->
    <xs:simpleType name="valid_permissions_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="RV"/>
            <xs:enumeration value="V"/>
            <xs:enumeration value="M"/>
            <xs:enumeration value="D"/>
            <xs:enumeration value="CR"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- allow_type -->
    <xs:complexType name="allow_type">
        <xs:simpleContent>
            <xs:extension base="valid_permissions_type">
                <xs:attribute name="group" type="group_types" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- permissions tag -->
    <xs:complexType name="permissions_type" mixed="true">
        <xs:sequence>
            <xs:element name="allow" type="allow_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <!-- complete document -->
    <xs:element name="knora">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="permissions" type="permissions_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="resource" type="resource_type" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="default-ontology" type="xs:string"/>
            <xs:attribute name="shortcode" type="knorashortcode_type"/>
        </xs:complexType>
        <xs:key name="permissionsId">
            <xs:selector xpath="./permissions"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="permissionsIdref" refer="permissionsId">
            <xs:selector xpath="resource"/>
            <xs:field xpath="@permissions"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== dasch-swiss/dsp-tools/testdata/dsp-ingest-data/dsp-ingest.xml
<?xml version="1.0" encoding="UTF-8"?>
<knora xmlns="https://dasch.swiss/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://dasch.swiss/schema https://raw.githubusercontent.com/dasch-swiss/dsp-tools/main/src/dsp_tools/resources/schema/data.xsd" shortcode="00A2" default-ontology="dog">
    <permissions id="open">
        <allow group="UnknownUser">V</allow>
        <allow group="KnownUser">V</allow>
        <allow group="ProjectMember">D</allow>
        <allow group="ProjectAdmin">CR</allow>
    </permissions>

    <resource label="Fluffy Image" restype=":Image2D" id="Fluffy1" permissions="open">
        <bitstream permissions="open">images/Fluffy.jpg</bitstream>
        <text-prop name=":hasAttribution">
            <text permissions="open" encoding="utf8">Columbus Metropolitan Library, Public domain, via Wikimedia Commons</text>
        </text-prop>
        <uri-prop name=":hasSourceLink">
            <uri permissions="open">https://commons.wikimedia.org/wiki/File:Siberian_Husky_dog_-_DPLA_-_b729034a262a5abba8f565574bb84dae.jpg</uri>
        </uri-prop>
    </resource>

    <resource label="Fluffy Image" restype=":Image2D" id="Fluffy2" permissions="open">
        <bitstream permissions="open">images/subFolder/Fluffy.jpg</bitstream>
        <text-prop name=":hasAttribution">
            <text permissions="open" encoding="utf8">Columbus Metropolitan Library, Public domain, via Wikimedia Commons</text>
        </text-prop>
        <uri-prop name=":hasSourceLink">
            <uri permissions="open">https://commons.wikimedia.org/wiki/File:Siberian_Husky_dog_-_DPLA_-_5248117eea26fda68834d39ebc90f925.jpg</uri>
        </uri-prop>
    </resource>

    <resource label="Shiba Inu Image" restype=":Image2D" id="Shiba" permissions="open">
        <bitstream permissions="open">images/subFolder/ShibaInu.jpg</bitstream>
        <text-prop name=":hasAttribution">
            <text permissions="open" encoding="utf8">Picography, CC0, via Wikimedia Commons</text>
        </text-prop>
        <uri-prop name=":hasSourceLink">
            <uri permissions="open">https://commons.wikimedia.org/wiki/File:Picography-shiba-inu-dog-forest-walk-sm-1.jpg</uri>
        </uri-prop>
    </resource>

    <resource label="Good Girl Image" restype=":Image2D" id="GoodGirlImage" permissions="open">
        <bitstream permissions="open">images/GoodGirl.jpg</bitstream>
        <text-prop name=":hasAttribution">
            <text permissions="open" encoding="utf8">Oldsingerman20, CC0, via Wikimedia Commons</text>
        </text-prop>
        <uri-prop name=":hasSourceLink">
            <uri permissions="open">https://commons.wikimedia.org/wiki/File:New_Guinea_Singing_Dog_looking_up.jpg</uri>
        </uri-prop>
    </resource>

    <resource label="Fluffy" restype=":Dog" id="Fluffy" permissions="open">
        <resptr-prop name=":hasImage">
            <resptr permissions="open">Fluffy1</resptr>
            <resptr permissions="open">Fluffy2</resptr>
        </resptr-prop>
    </resource>
    
    <resource label="Shiba" restype=":Dog" id="ShibaDog" permissions="open">
        <resptr-prop name=":hasImage">
            <resptr permissions="open">Shiba</resptr>
        </resptr-prop>
    </resource>

    <resource label="Good Girl" restype=":Dog" id="GoodGirl" permissions="open">
        <resptr-prop name=":hasImage">
            <resptr permissions="open">GoodGirlImage</resptr>
        </resptr-prop>
    </resource>
</knora>

=== dasch-swiss/dsp-tools/testdata/validate-data/generic/cardinality_violation.xml
<?xml version='1.0' encoding='utf-8'?>

<knora xmlns="https://dasch.swiss/schema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://dasch.swiss/schema ../../../src/dsp_tools/resources/schema/data.xsd"
       shortcode="9999"
       default-ontology="onto">

    <!-- 5 Violations -->

    <!-- 'testBoolean' cardinality 1 -->
    <resource label="Bool Card 1" restype=":ClassInheritedCardinalityOverwriting" id="id_card_one"/>

    <!-- This class does not have a cardinality for the property -->
    <resource label="Int card does not exist" restype=":CardOneResource" id="id_closed_constraint">
        <integer-prop name=":testIntegerSimpleText">
            <integer>1</integer>
        </integer-prop>
    </resource>

    <!-- 'testDecimalSimpleText' max cardinality 1 -->
    <resource label="Decimal Card 0-1" restype=":ClassMixedCard" id="id_max_card">
        <boolean-prop name=":testBoolean">
            <boolean>true</boolean>
        </boolean-prop>
        <resptr-prop name=":testHasLinkToCardOneResource">
            <resptr>id_closed_constraint</resptr>
            <resptr>id_card_one</resptr>
        </resptr-prop>
        <geoname-prop name=":testGeoname">
            <geoname>111111</geoname>
        </geoname-prop>
    </resource>

    <!-- 'testGeoname' cardinality 1-n -->
    <resource label="Geoname Card 1-n" restype=":ClassMixedCard" id="id_min_card">
        <resptr-prop name=":testHasLinkToCardOneResource">
            <resptr>id_closed_constraint</resptr>
        </resptr-prop>
    </resource>

    <!--
        'testSuperDate' does not have a cardinality.
        The sub-property 'testSubDate1' has a cardinality.
        It is not allowed to use the super-property without an explicit cardinality.
    -->
    <resource label="Super property without cardinality" restype=":ClassWithEverything" id="super_prop_no_card">
        <date-prop name=":testSuperDate">
            <date>JULIAN:BCE:0700:BCE:0600</date>
        </date-prop>
    </resource>

</knora>

=== dasch-swiss/dsp-tools/testdata/id2iri/remove-resources/data.xml
<?xml version='1.0' encoding='utf-8'?>

<knora xmlns="https://dasch.swiss/schema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://dasch.swiss/schema ../../../src/dsp_tools/resources/schema/data.xsd"
       shortcode="4123"
       default-ontology="testonto">

    <resource label="no_replacements" restype=":foo" id="no_replacements">
        <text-prop name=":bar">
            <text encoding="xml">Text</text>
        </text-prop>
    </resource>

    <resource label="resptr_only" restype=":foo" id="resptr_only">
        <text-prop name=":bar">
            <text encoding="xml">Text</text>
        </text-prop>
        <resptr-prop name=":foo-bar">
            <resptr>no_replacements</resptr>
            <resptr>salsah_link_only</resptr>
        </resptr-prop>
    </resource>

    <resource label="salsah_link_only" restype=":foo" id="salsah_link_only">
        <text-prop name=":bar">
            <text encoding="xml">
                Text with a <a class="salsah-link" href="IRI:no_replacements:IRI">link to no_replacements</a>
            </text>
        </text-prop>
    </resource>

    <resource label="resptr_and_salsah_link" restype=":foo" id="resptr_and_salsah_link">
        <text-prop name=":bar">
            <text encoding="xml">
                Text with a <a class="salsah-link" href="IRI:no_replacements:IRI">link to no_replacements</a>
            </text>
        </text-prop>
        <resptr-prop name=":foo-bar">
            <resptr>no_replacements</resptr>
        </resptr-prop>
    </resource>

</knora>

=== dasch-swiss/dsp-tools/testdata/validate-data/erroneous_ontology/erroneous_ontology.xml
<?xml version='1.0' encoding='utf-8'?>

<knora xmlns="https://dasch.swiss/schema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://dasch.swiss/schema ../../../src/dsp_tools/resources/schema/data.xsd"
       shortcode="9991"
       default-ontology="error">

    <!--
        The API erroneously allows 0-n cardinalities for seqnum/isPartOf.
        Therefore, we cannot rely on the ontology to get it correct.
        We have to treat it as a special case.
    -->

    <!-- 6 Violations -->

    <!-- Target Resources for Links -->

    <resource label="Resource without Representation" restype=":TargetResource"
              id="target_res_without_representation_1"/>


    <resource label="Resource without Representation" restype=":TargetResource"
              id="target_res_without_representation_2"/>


    <!-- usage of knora-api seqnum/isPartOf: multiple usage -->

    <resource label="Image with sequence" restype=":ImageWithKnoraProp_ErroneousCards"
              id="knora_seqnum_is_part_of_multiple">
        <bitstream>testdata/bitstreams/test.jpeg</bitstream>
        <resptr-prop name="isPartOf">
            <resptr>target_res_without_representation_1</resptr>
            <resptr>target_res_without_representation_2</resptr>
        </resptr-prop>
        <integer-prop name="seqnum">
            <integer>1</integer>
            <integer>2</integer>
        </integer-prop>
    </resource>

    <!-- knora-api:isPartOf is missing in the ontology -->

    <resource label="Image with sequence" restype=":ImageWithKnoraProp_MissingIsPartOf"
              id="knora_missing_is_part_of">
        <bitstream>testdata/bitstreams/test.jpeg</bitstream>
        <integer-prop name="seqnum">
            <integer>1</integer>
        </integer-prop>
    </resource>

    <!-- knora-api:seqnum is missing in the ontology -->

    <resource label="Image with sequence" restype=":ImageWithKnoraProp_MissingSeqnum"
              id="knora_missing_seqnum">
        <bitstream>testdata/bitstreams/test.jpeg</bitstream>
        <resptr-prop name="isPartOf">
            <resptr>target_res_without_representation_1</resptr>
        </resptr-prop>
    </resource>


    <!-- sub-property usage of knora-api seqnum/isPartOf: multiple usage -->

    <resource label="Image with sequence" restype=":ImageWithSubProp_ErroneousCards"
              id="seqnum_isPartOf_sub_prop_usage_and_erroneous_card">
        <bitstream>testdata/bitstreams/test.jpeg</bitstream>
        <resptr-prop name=":testIsPartOf">
            <resptr>target_res_without_representation_1</resptr>
            <resptr>target_res_without_representation_2</resptr>
        </resptr-prop>
        <integer-prop name=":testSeqnum">
            <integer>1</integer>
            <integer>2</integer>
        </integer-prop>
    </resource>


    <!-- sub-property of isPartOf is missing in the ontology -->

    <resource label="Image with sequence" restype=":ImageWithSubProp_MissingIsPartOf"
              id="sub_prop_missing_is_part_of">
        <bitstream>testdata/bitstreams/test.jpeg</bitstream>
        <integer-prop name=":testSeqnum">
            <integer>1</integer>
        </integer-prop>
    </resource>

    <!-- sub-property of seqnum is missing in the ontology -->

    <resource label="Image with sequence" restype=":ImageWithSubProp_MissingSeqnum"
              id="sub_prop_missing_seqnum">
        <bitstream>testdata/bitstreams/test.jpeg</bitstream>
        <resptr-prop name=":testIsPartOf">
            <resptr>target_res_without_representation_1</resptr>
        </resptr-prop>
    </resource>

</knora>
