=== dasch-swiss/dsp-tools/knora/dsplib/schemas/data.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="https://dasch.swiss/schema"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://dasch.swiss/schema"
           elementFormDefault="qualified">

    <!-- data type for resrefs "ID|ID|..." -->
    <xs:simpleType name="resrefs_type">
        <xs:restriction base="xs:token">
            <xs:pattern value="([^|]+)(\|[^|]+)*"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- group type for allow..." -->
    <xs:simpleType name="group_types">
        <xs:restriction base="xs:token">
            <xs:pattern
                value="(UnknownUser|KnownUser|ProjectMember|Creator|ProjectAdmin|SystemAdmin|([\w-]+):([\w ]+))"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- data type for knora date -->
    <xs:simpleType name="knoradate_type">
        <xs:restriction base="xs:token">
            <xs:pattern
                value="(GREGORIAN:|JULIAN:)?(CE:|BCE:)?(\d{4})?(-\d{1,2})?(-\d{1,2})?(:CE|:BCE)?(:\d{4})?(-\d{1,2})?(-\d{1,2})?"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- data type for knora color -->
    <xs:simpleType name="knoracolor_type">
        <xs:restriction base="xs:token">
            <xs:pattern value="#([0-9a-fA-F]{3}){1,2}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- data type for knora interval -->
    <xs:simpleType name="knorainterval_type">
        <xs:restriction base="xs:token">
            <xs:pattern value="([+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)):([+-]?([0-9]+([.][0-9]*)?|[.][0-9]+))"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- encoding types -->
    <xs:simpleType name="encoding_types">
        <xs:restriction base="xs:string">
            <xs:enumeration value="utf8"/>
            <xs:enumeration value="xml"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- text value type -->
    <xs:complexType name="text_type" mixed="true">
        <xs:sequence>
            <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="encoding" type="encoding_types" use="required"/>
        <xs:attribute name="resrefs" type="resrefs_type"/>
        <xs:attribute name="comment" type="xs:string"/>
        <xs:attribute name="permissions" type="xs:NCName" use="required"/>
    </xs:complexType>

    <!-- color value type -->
    <xs:complexType name="color_type">
        <xs:simpleContent>
            <xs:extension base="knoracolor_type">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- date value type -->
    <xs:complexType name="date_type">
        <xs:simpleContent>
            <xs:extension base="knoradate_type">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- float value type -->
    <xs:complexType name="float_type">
        <xs:simpleContent>
            <xs:extension base="xs:float">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- geometry value type -->
    <xs:complexType name="geometry_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- geoname value type -->
    <xs:complexType name="geoname_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- list value type -->
    <xs:complexType name="list_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- iconclass value type -->
    <xs:complexType name="iconclass_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- integer value type -->
    <xs:complexType name="integer_type">
        <xs:simpleContent>
            <xs:extension base="xs:integer">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- interval value type -->
    <xs:complexType name="interval_type">
        <xs:simpleContent>
            <xs:extension base="knorainterval_type">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- period value type -->
    <xs:complexType name="period_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="resptr_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- time value type -->
    <xs:complexType name="time_type">
        <xs:simpleContent>
            <xs:extension base="xs:dateTime">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- decimal value type -->
    <xs:complexType name="decimal_type">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- uri value type -->
    <xs:complexType name="uri_type">
        <xs:simpleContent>
            <xs:extension base="xs:anyURI">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- boolean value type -->
    <xs:complexType name="boolean_type">
        <xs:simpleContent>
            <xs:extension base="xs:boolean">
                <xs:attribute name="comment" type="xs:string"/>
                <xs:attribute name="permissions" type="xs:NCName" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- textprop_type -->
    <xs:complexType name="textprop_type">
        <xs:sequence>
            <xs:element name="text" type="text_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- colorprop_type -->
    <xs:complexType name="colorprop_type">
        <xs:sequence>
            <xs:element name="color" type="color_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- dateprop_type -->
    <xs:complexType name="dateprop_type">
        <xs:sequence>
            <xs:element name="date" type="date_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- floatprop_type -->
    <xs:complexType name="floatprop_type">
        <xs:sequence>
            <xs:element name="float" type="float_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- geometryprop_type -->
    <xs:complexType name="geometryprop_type">
        <xs:sequence>
            <xs:element name="geometry" type="geometry_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- geonameprop_type -->
    <xs:complexType name="geonameprop_type">
        <xs:sequence>
            <xs:element name="geoname" type="geoname_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- listprop_type -->
    <xs:complexType name="listprop_type">
        <xs:sequence>
            <xs:element name="list" type="list_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="list" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- iconclassprop_type -->
    <xs:complexType name="iconclassprop_type">
        <xs:sequence>
            <xs:element name="iconclass" type="iconclass_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- integerprop_type -->
    <xs:complexType name="integerprop_type">
        <xs:sequence>
            <xs:element name="integer" type="integer_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- intervalprop_type -->
    <xs:complexType name="intervalprop_type">
        <xs:sequence>
            <xs:element name="interval" type="interval_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- periodprop_type -->
    <xs:complexType name="periodprop_type">
        <xs:sequence>
            <xs:element name="period" type="period_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- resptrprop_type -->
    <xs:complexType name="resptrprop_type">
        <xs:sequence>
            <xs:element name="resptr" type="resptr_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- timeprop_type -->
    <xs:complexType name="timeprop_type">
        <xs:sequence>
            <xs:element name="time" type="time_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- decimalprop_type -->
    <xs:complexType name="decimalprop_type">
        <xs:sequence>
            <xs:element name="decimal" type="decimal_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- uriprop_type -->
    <xs:complexType name="uriprop_type">
        <xs:sequence>
            <xs:element name="uri" type="uri_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- booleanprop_type -->
    <xs:complexType name="booleanprop_type">
        <xs:sequence>
            <xs:element name="boolean" type="boolean_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- bitsteeam tag -->
    <xs:complexType name="bitstream_type">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
    </xs:complexType>

    <!-- image tag -->
    <xs:complexType name="image_type">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
    </xs:complexType>

    <!-- sound tag -->
    <xs:complexType name="sound_type">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
    </xs:complexType>

    <!-- movie tag -->
    <xs:complexType name="movie_type">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
    </xs:complexType>

    <!-- movie tag -->
    <xs:complexType name="document_type">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
    </xs:complexType>

    <!-- resource tag -->
    <xs:complexType name="resource_type">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="1">
                <!--
                <xs:element name="image" type="image_type" />
                <xs:element name="sound" type="sound_type" />
                <xs:element name="movie" type="sound_type" />
                <xs:element name="document" type="sound_type" />
                -->
                <xs:element name="bitstream" type="sound_type"/>
            </xs:choice>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="text-prop" type="textprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="color-prop" type="colorprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="date-prop" type="dateprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="geometry-prop" type="geometryprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="geoname-prop" type="geonameprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="list-prop" type="listprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="iconclass-prop" type="iconclassprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="integer-prop" type="integerprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="interval-prop" type="intervalprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="period-prop" type="periodprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="resptr-prop" type="resptrprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="time-prop" type="timeprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="decimal-prop" type="decimalprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="uri-prop" type="uriprop_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="boolean-prop" type="booleanprop_type" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>

        </xs:sequence>
        <xs:attribute name="label" type="xs:string" use="required"/>
        <xs:attribute name="restype" type="xs:string" use="required"/>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="permissions" type="xs:NCName" use="required"/>
    </xs:complexType>

    <!-- data type for knora shortcode -->
    <xs:simpleType name="knorashortcode_type">
        <xs:restriction base="xs:token">
            <xs:pattern value="[0-9a-fA-F]{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- data type for valid permissions_type" -->
    <xs:simpleType name="valid_permissions_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="RV"/>
            <xs:enumeration value="V"/>
            <xs:enumeration value="M"/>
            <xs:enumeration value="D"/>
            <xs:enumeration value="CR"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- allow_type -->
    <xs:complexType name="allow_type">
        <xs:simpleContent>
            <xs:extension base="valid_permissions_type">
                <xs:attribute name="group" type="group_types" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- permissions tag -->
    <xs:complexType name="permissions_type" mixed="true">
        <xs:sequence>
            <xs:element name="allow" type="allow_type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <!-- complete document -->
    <xs:element name="knora">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="permissions" type="permissions_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="resource" type="resource_type" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="default-ontology" type="xs:string"/>
            <xs:attribute name="shortcode" type="knorashortcode_type"/>
        </xs:complexType>
        <xs:key name="permissionsId">
            <xs:selector xpath="./permissions"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="permissionsIdref" refer="permissionsId">
            <xs:selector xpath="resource"/>
            <xs:field xpath="@permissions"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== dasch-swiss/dsp-tools/testdata/validate-data/core_validation/value_type_violation.xml
<?xml version='1.0' encoding='utf-8'?>

<knora xmlns="https://dasch.swiss/schema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://dasch.swiss/schema ../../../src/dsp_tools/resources/schema/data.xsd"
       shortcode="9999"
       default-ontology="onto">

    <!--
        In this file, the property type does not match with the ontology.
        The content is valid (eg. a boolean is a valid boolean)
        For the text-prop the encoding was switched
     -->

    <resource label="Empty" restype=":ClassWithEverything" id="empty_ok"/>

    <resource label="Bool" restype=":ClassWithEverything" id="bool_wrong_value_type">
        <text-prop name=":testBoolean">
            <text encoding="utf8">true</text>
        </text-prop>
    </resource>

    <resource label="Color" restype=":ClassWithEverything" id="color_wrong_value_type">
        <text-prop name=":testColor">
            <text encoding="utf8">#00ff00</text>
        </text-prop>
    </resource>

    <resource label="Date" restype=":ClassWithEverything" id="date_wrong_value_type">
        <text-prop name=":testSubDate1">
            <text encoding="utf8">JULIAN:BCE:0700:BCE:0600</text>
        </text-prop>
    </resource>

    <resource label="Decimal" restype=":ClassWithEverything" id="decimal_wrong_value_type">
        <text-prop name=":testDecimalSimpleText">
            <text encoding="utf8">2.71</text>
        </text-prop>
    </resource>

    <resource label="Geoname" restype=":ClassWithEverything" id="geoname_wrong_value_type">
        <text-prop name=":testGeoname">
            <text encoding="utf8">1111111</text>
        </text-prop>
    </resource>

    <resource label="Integer" restype=":ClassWithEverything" id="integer_wrong_value_type">
        <text-prop name=":testIntegerSimpleText">
            <text encoding="utf8">1</text>
        </text-prop>
    </resource>

    <resource label="This should be an int value" restype=":ClassWithEverything" id="is_text_should_be_integer">
        <text-prop name=":testIntegerSpinbox">
            <text encoding="utf8">1</text>
        </text-prop>
    </resource>

    <resource label="List" restype=":ClassWithEverything" id="list_wrong_value_type">
        <text-prop name=":testListProp">
            <text encoding="utf8">n1</text>
        </text-prop>
    </resource>

    <resource label="Link Prop" restype=":ClassWithEverything" id="link_wrong_value_type">
        <text-prop name=":testHasLinkTo">
            <text encoding="utf8">id_1</text>
        </text-prop>
    </resource>

    <resource label="Preview Prop" restype=":ClassWithEverything" id="region_preview_wrong_type">
        <region-preview-prop name=":testHasRegionPreview">
            <region-preview>empty_ok</region-preview>
        </region-preview-prop>
    </resource>

    <resource label="Richtext" restype=":ClassWithEverything" id="richtext_wrong_value_type">
        <text-prop name=":testRichtext">
            <text encoding="utf8"><p>Text</p></text>
        </text-prop>
    </resource>

    <resource label="Simpletext" restype=":ClassWithEverything" id="simpletext_wrong_value_type">
        <text-prop name=":testTextarea">
            <text encoding="xml">Text</text>
        </text-prop>
    </resource>

    <resource label="This should be a text value" restype=":ClassWithEverything" id="is_link_should_be_text">
        <resptr-prop name=":testTextarea">
            <resptr>link_non_existing</resptr>
        </resptr-prop>
    </resource>

    <resource label="Should be simple text" restype=":ClassWithEverything" id="is_date_should_be_simpletext">
        <date-prop name=":testTextarea">
            <date>JULIAN:BCE:0700:BCE:0600</date>
        </date-prop>
    </resource>

    <resource label="Time" restype=":ClassWithEverything" id="time_wrong_value_type">
        <text-prop name=":testTimeValue">
            <text encoding="utf8">2019-10-23T13:45:12.01-14:00</text>
        </text-prop>
    </resource>

    <resource label="Uri" restype=":ClassWithEverything" id="uri_wrong_value_type">
        <text-prop name=":testUriValue">
            <text encoding="utf8">https://dasch.swiss</text>
        </text-prop>
    </resource>

</knora>

=== dasch-swiss/dsp-tools/testdata/xml-validate/data/cardinality_correct.xml
<?xml version='1.0' encoding='utf-8'?>

<knora xmlns="https://dasch.swiss/schema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://dasch.swiss/schema ../../../src/dsp_tools/resources/schema/data.xsd"
       shortcode="9999"
       default-ontology="onto">

    <resource label="Empty" restype=":ClassWithEverything" id="id_0"/>

    <resource label="Card 0-1" restype=":ClassInheritedCardinality" id="id_1">
        <boolean-prop name=":testBoolean">
            <boolean>true</boolean>
        </boolean-prop>
    </resource>

    <resource label="Card 1" restype=":ClassInheritedCardinalityOverwriting" id="id_2">
        <boolean-prop name=":testBoolean">
            <boolean>true</boolean>
        </boolean-prop>
    </resource>

    <resource label="Card Mixed" restype=":ClassInheritedCardinalityOverwriting" id="id_3">
        <boolean-prop name=":testBoolean">
            <boolean>true</boolean>
        </boolean-prop>
        <decimal-prop name=":testDecimalSimpleText">
            <decimal>2.71</decimal>
        </decimal-prop>
        <integer-prop name=":testIntegerSimpleText">
            <integer>1</integer>
            <integer>2</integer>
        </integer-prop>
        <decimal-prop name=":testDecimalSpinbox">
            <decimal>2.71</decimal>
            <decimal>2.00</decimal>
        </decimal-prop>
    </resource>

</knora>
