=== dasch-swiss/dsp-tools/knora/dsplib/schemas/lists-only.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dasch.swiss/schema/list-only.json",
    "title": "JSON schema for DSP lists",
    "description": "JSON schema for the lists section used in DSP ontologies",
    "definitions": {
        "label": {
            "type": "object",
            "patternProperties": {
                "^(en|de|fr|it)": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "comment": {
            "type": "object",
            "patternProperties": {
                "^(en|de|fr|it)": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "node": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "labels": {
                    "$ref": "#/definitions/label"
                },
                "comments": {
                    "$ref": "#/definitions/comment"
                },
                "nodes": {
                    "oneOf": [
                        {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/node"
                            }
                        },
                        {
                            "type": "object",
                            "$ref": "#/definitions/excelref"
                        }
                    ]
                }
            },
            "required": [
                "name",
                "labels"
            ],
            "additionalProperties": false
        },
        "excelref": {
            "type": "object",
            "properties": {
                "file": {
                    "type": "string"
                },
                "worksheet": {
                    "type": "string"
                },
                "startrow": {
                    "type": "integer"
                },
                "startcol": {
                    "type": "integer"
                }
            },
            "required": [
                "file",
                "worksheet"
            ]
        }
    },
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "labels": {
            "$ref": "#/definitions/label"
        },
        "comments": {
            "$ref": "#/definitions/comment"
        },
        "nodes": {
            "oneOf": [
                {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node"
                    }
                },
                {
                    "type": "object",
                    "$ref": "#/definitions/excelref"
                }
            ]
        }
    },
    "required": [
        "name",
        "nodes"
    ],
    "additionalProperties": false
}

=== dasch-swiss/dsp-tools/testdata/excel2json/new-lists-output-expected.json
[
  {
    "name": "List 1",
    "labels": {
      "en": "List 1",
      "de": "Liste 1"
    },
    "comments": {
      "en": "Comments List",
      "de": "Kommentar Liste"
    },
    "nodes": [
      {
        "name": "List 1:Node 1",
        "labels": {
          "de": "Knoten 1",
          "en": "Node 1"
        },
        "nodes": [
          {
            "name": "Node 1.1",
            "labels": {
              "de": "Knoten 1.1",
              "en": "Node 1.1"
            },
            "nodes": [
              {
                "name": "custom_name_1-1-1",
                "labels": {
                  "de": "Knoten 1.1.1",
                  "en": "Node 1.1.1"
                }
              },
              {
                "name": "custom_name_1-1-2",
                "labels": {
                  "de": "Knoten 1.1.2",
                  "en": "Node 1.1.2"
                }
              }
            ]
          }
        ]
      },
      {
        "name": "List 1:Node 2",
        "labels": {
          "de": "Knoten 2",
          "en": "Node 2"
        },
        "nodes": [
          {
            "name": "Node 2.1",
            "labels": {
              "de": "Knoten 2.1",
              "en": "Node 2.1"
            },
            "comments": {
              "de": "Kommentar N2.1",
              "en": "Comments N2.1"
            }
          },
          {
            "name": "Node 2.2",
            "labels": {
              "de": "Knoten 2.2",
              "en": "Node 2.2"
            }
          },
          {
            "name": "Node 2.3",
            "labels": {
              "de": "Knoten 2.3",
              "en": "Node 2.3"
            }
          }
        ]
      },
      {
        "name": "List 1:Node 3",
        "labels": {
          "de": "Knoten 3",
          "en": "Node 3"
        },
        "comments": {
          "de": "Kommentar N3",
          "en": "Comments N3"
        }
      }
    ]
  },
  {
    "name": "List 2",
    "labels": {
      "en": "List 2"
    },
    "comments": {
      "en": "Comment List"
    },
    "nodes": [
      {
        "name": "List 2:Node 1",
        "labels": {
          "en": "Node 1"
        },
        "comments": {
          "en": "Comment N1"
        },
        "nodes": [
          {
            "name": "List 2:Node 1:subnode1",
            "labels": {
              "en": "subnode1"
            },
            "comments": {
              "en": "Comment N1.1"
            }
          }
        ]
      },
      {
        "name": "List 2:Node 2",
        "labels": {
          "en": "Node 2"
        },
        "comments": {
          "en": "Comment N2"
        },
        "nodes": [
          {
            "name": "List 2:Node 2:subnode1",
            "labels": {
              "en": "subnode1"
            },
            "comments": {
              "en": "Comment N2.1"
            }
          }
        ]
      }
    ]
  },
  {
    "name": "list 3 id",
    "labels": {
      "en": "List 3"
    },
    "comments": {
      "en": "List 3"
    },
    "nodes": [
      {
        "name": "List 3:Node 1",
        "labels": {
          "en": "Node 1"
        },
        "nodes": [
          {
            "name": "sub1",
            "labels": {
              "en": "sub1"
            }
          }
        ]
      },
      {
        "name": "List 3:Node 2",
        "labels": {
          "en": "Node 2"
        }
      },
      {
        "name": "List 3:Node 3",
        "labels": {
          "en": "Node 3"
        },
        "nodes": [
          {
            "name": "List 3:Node 3:sub1",
            "labels": {
              "en": "sub1"
            }
          }
        ]
      },
      {
        "name": "Node 4",
        "labels": {
          "en": "Node 4"
        }
      }
    ]
  }
]

=== dasch-swiss/dsp-tools/testdata/excel2json/old-lists-multilingual-output-expected.json
[
    {
        "name": "first-list",
        "labels": {
            "fr": "première liste",
            "en": "first list",
            "de": "erste Liste"
        },
        "comments": {
            "fr": "première liste",
            "en": "first list",
            "de": "erste Liste"
        },
        "nodes": [
            {
                "name": "special-characters-12-0-are-embedded",
                "labels": {
                    "fr": "caractères spéciales 1&2-%*_0 dedans",
                    "en": "special characters 1&2-%*_0 are embedded",
                    "de": "Spezialzeichen 1&2-%*_0 sind eingebettet"
                },
                "nodes": [
                    {
                        "name": "very",
                        "labels": {
                            "fr": "très",
                            "en": "very",
                            "de": "sehr"
                        },
                        "nodes": [
                            {
                                "name": "deeply",
                                "labels": {
                                    "fr": "profondément",
                                    "en": "deeply",
                                    "de": "tief"
                                },
                                "nodes": [
                                    {
                                        "name": "nested",
                                        "labels": {
                                            "fr": "niché!",
                                            "en": "nested!",
                                            "de": "verschachtelt!"
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "name": "second-list",
        "labels": {
            "fr": "deuxième liste",
            "en": "second list",
            "de": "zweite Liste"
        },
        "comments": {
            "fr": "deuxième liste",
            "en": "second list",
            "de": "zweite Liste"
        },
        "nodes": [
            {
                "name": "first-node",
                "labels": {
                    "fr": "premier noeud",
                    "en": "first node",
                    "de": "erster Knoten"
                }
            },
            {
                "name": "duplicate-nodename",
                "labels": {
                    "fr": "noeud doublé",
                    "en": "duplicate nodename",
                    "de": "Doppelung"
                }
            },
            {
                "name": "duplicate-nodename-2",
                "labels": {
                    "fr": "noeud doublé!",
                    "en": "duplicate nodename!",
                    "de": "Doppelung!"
                }
            },
            {
                "name": "duplicate-nodename-3",
                "labels": {
                    "fr": "noeud doublé?",
                    "en": "duplicate nodename?",
                    "de": "Doppelung?"
                }
            }
        ]
    }
]
